# Generated by Django 4.1.7 on 2023-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(default='', max_length=122)),
                ('prod_name', models.CharField(default='', max_length=122)),
                ('prod_desc', models.CharField(default='', max_length=122)),
                ('prod_start_price', models.IntegerField(default=0)),
                ('prod_price', models.IntegerField(default=0)),
            ],
        ),
    ]
