# Generated by Django 4.1.7 on 2023-02-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='artist',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='seller',
            field=models.CharField(default='', max_length=122),
        ),
    ]
