# Generated by Django 4.1.7 on 2023-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionproduct_artist_auctionproduct_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='prod_image',
            field=models.ImageField(default='something.img', upload_to='images/'),
        ),
    ]
