# Generated by Django 4.1.7 on 2023-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auctionproduct_prod_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=122)),
                ('user_id', models.IntegerField(default=0, unique='true')),
                ('user_email', models.CharField(default='', max_length=122)),
                ('password', models.CharField(default='', max_length=122)),
            ],
        ),
    ]
