# Generated by Django 4.1.7 on 2023-03-04 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_user_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='duration_mins',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 1, 59, 43, 465966)),
        ),
        migrations.AddField(
            model_name='auctionproduct',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 1, 59, 43, 465966)),
        ),
    ]
