# Generated by Django 4.1.7 on 2023-03-04 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auctionproduct_duration_mins_auctionproduct_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 3, 0, 24, 324273)),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 3, 0, 24, 324273)),
        ),
    ]
