# Generated by Django 4.1.7 on 2023-02-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_contact_desc_contact_email_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default='2023-01-30'),
        ),
    ]
